title: Ramchander Bhaskara
description: ""
author: Rcb

theme: minima

base_url: /ram-bhaskara.github.io
repository: ram-bhaskara/ram-bhaskara.github.io

# Minima social links
github_username: ram-bhaskara
linkedin_username: ram-chander
email: ramchanderbhaskara@gmail.com
google_scholar: 77pyaSYAAAAJ
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/CV.md
  - _pages/publicationList.md
  #- _pages/about.md
  #- _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md


gems:
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: "./_bibliography/references.bib"
  bibliography_template: "{{reference}}"
